### ISSUE TITLE
How to quickly find the fixed point?

### ISSUE THREAD

**Issue by lcqliu** [kul-arun/orbital-evolution-of-extreme-mass-ratio-inspirals#1]
I don't know how to quickly find the fixed point,  could you add the code for these purpose?

**Comment by kul-arun** [comment]
There is no analytical way to find the fixed point u_0. This point essentially corresponds to circular orbits that always cross the equatorial plane at the same point. It is calculated through trial and error. The orbits are evolved by varying the initial value of the r coordinate, till we get the plot of the orbit in the (r, theta)-plane as a straight line (as seen in the notebook). This line is perpendicular to the r-axis since the value of r does not change for circular orbits. A rough estimate of the r coordinate should be sufficient to perform the computations.

The fixed point will change when we introduce changes in the metric parameters or when we use different values for the specific energy and the specific angular momentum.  I shall update the notebook to include this information.

**Comment by lcqliu** [comment]
for  the initial value :the initial_state = get_initial_state(r, np.pi/2, 0.0, 0.1), as th dr/dt=0.1,  I find it is difficult to find the plots of the orbit in the (r, theta)-plane as a straight line,   what should be change?
